name: scoped-labels
version: 0.1.0.0
github: "dannypsnl/scoped-labels"
license: BSD3
author: "Lîm Tsú-thuàn"
maintainer: "dannypsnl@gmail.com"
copyright: "2021 Lîm Tsú-thuàn"

extra-source-files:
  - README.md
  - ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description: Please see the README on GitHub at <https://github.com/githubuser/scoped-labels#readme>

dependencies:
  - base >= 4.7 && < 5
  - exceptions >= 0.10.4
  - containers >= 0.6.5.1

library:
  source-dirs: src

executables:
  scoped-labels-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - scoped-labels

tests:
  scoped-labels-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - scoped-labels
